version: "3.9"

services:
  backend-service:
    build: ./
    container_name: backend-service
    restart: unless-stopped
    ports:
      - '8083:8083'

  h2:
    image: buildo/h2database
    container_name: h2
    ports:
      - '8081:8082'


