server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baselineOnMigrate: true
  h2:
    console:
      enabled: true
      path: /h2-console

cache:
  type: LRU
  maxSize: 10
